package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/audworth/comments-system/internal/application/comment"
	"github.com/audworth/comments-system/internal/application/post"
	grapherror "github.com/audworth/comments-system/internal/transport/graph/error"
	"github.com/audworth/comments-system/internal/transport/graph/generated"
	"github.com/audworth/comments-system/internal/transport/graph/graphscalar"
	"github.com/audworth/comments-system/internal/transport/graph/model"
	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	authorID, err := uuid.Parse(input.AuthorID)
	if err != nil {
		return nil, grapherror.InvalidID("authorId", err)
	}

	p, err := r.posts.Publish(ctx, post.PublishParams{
		AuthorID:        authorID,
		Title:           input.Title,
		Body:            input.Body,
		CommentsEnabled: input.CommentsEnabled,
	})
	if err != nil {
		return nil, err
	}

	return model.PostFromDomain(p), nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, input model.SetPostCommentsEnabledInput) (*model.Post, error) {
	postID, err := uuid.Parse(input.PostID)
	if err != nil {
		return nil, grapherror.InvalidID("postId", err)
	}
	authorID, err := uuid.Parse(input.AuthorID)
	if err != nil {
		return nil, grapherror.InvalidID("authorId", err)
	}

	p, err := r.posts.SetCommentsEnabled(ctx, postID, authorID, input.Enabled)
	if err != nil {
		return nil, err
	}
	return model.PostFromDomain(p), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	postID, err := uuid.Parse(input.PostID)
	if err != nil {
		return nil, grapherror.InvalidID("postId", err)
	}
	authorID, err := uuid.Parse(input.AuthorID)
	if err != nil {
		return nil, grapherror.InvalidID("authorId", err)
	}

	var parentID *uuid.UUID
	if input.ParentID != nil {
		parsed, err := uuid.Parse(*input.ParentID)
		if err != nil {
			return nil, grapherror.InvalidID("parentId", err)
		}
		parentID = &parsed
	}

	comm, err := r.comments.Publish(ctx, comment.PublishParams{
		PostID:   postID,
		ParentID: parentID,
		AuthorID: authorID,
		Body:     input.Body,
	})
	if err != nil {
		return nil, err
	}
	return model.CommentFromDomain(comm), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int32, after *graphscalar.Cursor) (*model.PostConnection, error) {
	var pos *post.Position
	if after != nil {
		decoded, err := graphscalar.DecodeCursor(*after)
		if err != nil {
			return nil, grapherror.InvalidCursor(err)
		}
		pos = &post.Position{
			CreatedAt: decoded.CreatedAt,
			ID:        decoded.ID,
		}
	}

	posts, err := r.posts.List(ctx, post.ListParams{
		Limit: int(first),
		After: pos,
	})
	if err != nil {
		return nil, err
	}

	return model.PostConnectionFromPage(posts)
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := uuid.Parse(id)
	if err != nil {
		return nil, grapherror.InvalidID("postId", err)
	}

	p, err := r.posts.GetByID(ctx, postID)
	if err != nil {
		return nil, err
	}

	return model.PostFromDomain(p), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	commID, err := uuid.Parse(id)
	if err != nil {
		return nil, grapherror.InvalidID("commentId", err)
	}

	comm, err := r.comments.GetByID(ctx, commID)
	if err != nil {
		return nil, err
	}

	return model.CommentFromDomain(comm), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, parentID *string, first int32, after *graphscalar.Cursor) (*model.CommentConnection, error) {
	parsedPostID, err := uuid.Parse(postID)
	if err != nil {
		return nil, grapherror.InvalidID("postId", err)
	}

	var parsedParentID *uuid.UUID
	if parentID != nil {
		parsed, err := uuid.Parse(*parentID)
		if err != nil {
			return nil, grapherror.InvalidID("parentId", err)
		}
		parsedParentID = &parsed
	}

	var pos *comment.Position
	if after != nil {
		decoded, err := graphscalar.DecodeCursor(*after)
		if err != nil {
			return nil, grapherror.InvalidCursor(err)
		}
		pos = &comment.Position{
			CreatedAt: decoded.CreatedAt,
			ID:        decoded.ID,
		}
	}

	comms, err := r.comments.List(ctx, comment.ListParams{
		PostID:   parsedPostID,
		ParentID: parsedParentID,
		Limit:    int(first),
		After:    pos,
	})
	if err != nil {
		return nil, err
	}

	return model.CommentConnectionFromPage(comms)
}

// CommentCreated is the resolver for the commentCreated field.
func (r *subscriptionResolver) CommentCreated(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentCreated - commentCreated"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
