// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/audworth/comments-system/internal/transport/graph/resolver (interfaces: PostsService,UsersService,CommentsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=resolver . PostsService,UsersService,CommentsService
//

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	comment "github.com/audworth/comments-system/internal/application/comment"
	post "github.com/audworth/comments-system/internal/application/post"
	domain "github.com/audworth/comments-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPostsService is a mock of PostsService interface.
type MockPostsService struct {
	ctrl     *gomock.Controller
	recorder *MockPostsServiceMockRecorder
	isgomock struct{}
}

// MockPostsServiceMockRecorder is the mock recorder for MockPostsService.
type MockPostsServiceMockRecorder struct {
	mock *MockPostsService
}

// NewMockPostsService creates a new mock instance.
func NewMockPostsService(ctrl *gomock.Controller) *MockPostsService {
	mock := &MockPostsService{ctrl: ctrl}
	mock.recorder = &MockPostsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsService) EXPECT() *MockPostsServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPostsService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostsServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostsService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPostsService) List(ctx context.Context, params post.ListParams) (*post.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*post.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPostsServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostsService)(nil).List), ctx, params)
}

// Publish mocks base method.
func (m *MockPostsService) Publish(ctx context.Context, params post.PublishParams) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, params)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockPostsServiceMockRecorder) Publish(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPostsService)(nil).Publish), ctx, params)
}

// SetCommentsEnabled mocks base method.
func (m *MockPostsService) SetCommentsEnabled(ctx context.Context, postID, authorID uuid.UUID, enabled bool) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommentsEnabled", ctx, postID, authorID, enabled)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCommentsEnabled indicates an expected call of SetCommentsEnabled.
func (mr *MockPostsServiceMockRecorder) SetCommentsEnabled(ctx, postID, authorID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommentsEnabled", reflect.TypeOf((*MockPostsService)(nil).SetCommentsEnabled), ctx, postID, authorID, enabled)
}

// MockUsersService is a mock of UsersService interface.
type MockUsersService struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceMockRecorder
	isgomock struct{}
}

// MockUsersServiceMockRecorder is the mock recorder for MockUsersService.
type MockUsersServiceMockRecorder struct {
	mock *MockUsersService
}

// NewMockUsersService creates a new mock instance.
func NewMockUsersService(ctrl *gomock.Controller) *MockUsersService {
	mock := &MockUsersService{ctrl: ctrl}
	mock.recorder = &MockUsersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersService) EXPECT() *MockUsersServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUsersService) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsersServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsersService)(nil).GetByID), ctx, id)
}

// MockCommentsService is a mock of CommentsService interface.
type MockCommentsService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentsServiceMockRecorder
	isgomock struct{}
}

// MockCommentsServiceMockRecorder is the mock recorder for MockCommentsService.
type MockCommentsServiceMockRecorder struct {
	mock *MockCommentsService
}

// NewMockCommentsService creates a new mock instance.
func NewMockCommentsService(ctrl *gomock.Controller) *MockCommentsService {
	mock := &MockCommentsService{ctrl: ctrl}
	mock.recorder = &MockCommentsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentsService) EXPECT() *MockCommentsServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCommentsService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentsServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentsService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCommentsService) List(ctx context.Context, params comment.ListParams) (*comment.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*comment.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommentsServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommentsService)(nil).List), ctx, params)
}

// Publish mocks base method.
func (m *MockCommentsService) Publish(ctx context.Context, params comment.PublishParams) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, params)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockCommentsServiceMockRecorder) Publish(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCommentsService)(nil).Publish), ctx, params)
}

// SubscribeToPostComments mocks base method.
func (m *MockCommentsService) SubscribeToPostComments(ctx context.Context, postID uuid.UUID) (<-chan *domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToPostComments", ctx, postID)
	ret0, _ := ret[0].(<-chan *domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToPostComments indicates an expected call of SubscribeToPostComments.
func (mr *MockCommentsServiceMockRecorder) SubscribeToPostComments(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToPostComments", reflect.TypeOf((*MockCommentsService)(nil).SubscribeToPostComments), ctx, postID)
}
