// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/audworth/comments-system/internal/transport/graph/resolver (interfaces: PostsService,UsersService,CommentsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=resolver . PostsService,UsersService,CommentsService
//

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	comment "github.com/audworth/comments-system/internal/application/comment"
	post "github.com/audworth/comments-system/internal/application/post"
	domain "github.com/audworth/comments-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPostsService is a mock of PostsService interface.
type MockPostsService struct {
	ctrl     *gomock.Controller
	recorder *MockPostsServiceMockRecorder
	isgomock struct{}
}

// MockPostsServiceMockRecorder is the mock recorder for MockPostsService.
type MockPostsServiceMockRecorder struct {
	mock *MockPostsService
}

// NewMockPostsService creates a new mock instance.
func NewMockPostsService(ctrl *gomock.Controller) *MockPostsService {
	mock := &MockPostsService{ctrl: ctrl}
	mock.recorder = &MockPostsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsService) EXPECT() *MockPostsServiceMockRecorder {
	return m.recorder
}

// ListPosts mocks base method.
func (m *MockPostsService) ListPosts(ctx context.Context, params *post.ListParams) (*post.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx, params)
	ret0, _ := ret[0].(*post.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockPostsServiceMockRecorder) ListPosts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockPostsService)(nil).ListPosts), ctx, params)
}

// PostByID mocks base method.
func (m *MockPostsService) PostByID(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostByID", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostByID indicates an expected call of PostByID.
func (mr *MockPostsServiceMockRecorder) PostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostByID", reflect.TypeOf((*MockPostsService)(nil).PostByID), ctx, id)
}

// PublishNewPost mocks base method.
func (m *MockPostsService) PublishNewPost(ctx context.Context, params *post.NewPostParams) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishNewPost", ctx, params)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishNewPost indicates an expected call of PublishNewPost.
func (mr *MockPostsServiceMockRecorder) PublishNewPost(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishNewPost", reflect.TypeOf((*MockPostsService)(nil).PublishNewPost), ctx, params)
}

// SetCommentsToEnabled mocks base method.
func (m *MockPostsService) SetCommentsToEnabled(ctx context.Context, postID, authorID uuid.UUID, enabled bool) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommentsToEnabled", ctx, postID, authorID, enabled)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCommentsToEnabled indicates an expected call of SetCommentsToEnabled.
func (mr *MockPostsServiceMockRecorder) SetCommentsToEnabled(ctx, postID, authorID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommentsToEnabled", reflect.TypeOf((*MockPostsService)(nil).SetCommentsToEnabled), ctx, postID, authorID, enabled)
}

// MockUsersService is a mock of UsersService interface.
type MockUsersService struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceMockRecorder
	isgomock struct{}
}

// MockUsersServiceMockRecorder is the mock recorder for MockUsersService.
type MockUsersServiceMockRecorder struct {
	mock *MockUsersService
}

// NewMockUsersService creates a new mock instance.
func NewMockUsersService(ctrl *gomock.Controller) *MockUsersService {
	mock := &MockUsersService{ctrl: ctrl}
	mock.recorder = &MockUsersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersService) EXPECT() *MockUsersServiceMockRecorder {
	return m.recorder
}

// UserByID mocks base method.
func (m *MockUsersService) UserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockUsersServiceMockRecorder) UserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockUsersService)(nil).UserByID), ctx, id)
}

// MockCommentsService is a mock of CommentsService interface.
type MockCommentsService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentsServiceMockRecorder
	isgomock struct{}
}

// MockCommentsServiceMockRecorder is the mock recorder for MockCommentsService.
type MockCommentsServiceMockRecorder struct {
	mock *MockCommentsService
}

// NewMockCommentsService creates a new mock instance.
func NewMockCommentsService(ctrl *gomock.Controller) *MockCommentsService {
	mock := &MockCommentsService{ctrl: ctrl}
	mock.recorder = &MockCommentsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentsService) EXPECT() *MockCommentsServiceMockRecorder {
	return m.recorder
}

// CommentByID mocks base method.
func (m *MockCommentsService) CommentByID(ctx context.Context, id uuid.UUID) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentByID indicates an expected call of CommentByID.
func (mr *MockCommentsServiceMockRecorder) CommentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentByID", reflect.TypeOf((*MockCommentsService)(nil).CommentByID), ctx, id)
}

// List mocks base method.
func (m *MockCommentsService) List(ctx context.Context, params *comment.ListParams) (*comment.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*comment.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommentsServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommentsService)(nil).List), ctx, params)
}

// PublishNewComment mocks base method.
func (m *MockCommentsService) PublishNewComment(ctx context.Context, params *comment.NewCommentParams) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishNewComment", ctx, params)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishNewComment indicates an expected call of PublishNewComment.
func (mr *MockCommentsServiceMockRecorder) PublishNewComment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishNewComment", reflect.TypeOf((*MockCommentsService)(nil).PublishNewComment), ctx, params)
}
