// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/audworth/comments-system/internal/application/user (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=user . Repository
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	domain "github.com/audworth/comments-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// UserByID mocks base method.
func (m *MockRepository) UserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockRepositoryMockRecorder) UserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockRepository)(nil).UserByID), ctx, id)
}

// UsersByIDs mocks base method.
func (m *MockRepository) UsersByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersByIDs indicates an expected call of UsersByIDs.
func (mr *MockRepositoryMockRecorder) UsersByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersByIDs", reflect.TypeOf((*MockRepository)(nil).UsersByIDs), ctx, ids)
}
