version: "3"
dotenv: [".env"]

vars:
  GO_PACKAGES: ./...

tasks:
  default:
    desc: доступные таски
    silent: true
    cmds:
      - task --list

  tidy:
    desc: обновить go.mod и go.sum
    cmds:
      - go mod tidy

  generate:
    desc: сгенерировать моки и код из схем GraphQL
    cmds:
      - go generate ./internal/application/...
      - go generate ./internal/transport/graph/resolver
      - go tool gqlgen generate

  lint:
    desc: запустить линтер
    cmds:
      - golangci-lint run {{.GO_PACKAGES}}

  test:
    desc: запустить юнит тесты
    cmds:
      - >-
        go test
        -race
        {{.GO_PACKAGES}}

  migrate:
    desc: применить все миграции
    cmds:
      - go run ./cmd/migrate

  seed:
    desc: пересоздать нагрузочные сиды, удалив текущие данные
    cmds:
      - >-
        docker compose exec -T postgres
        psql
        --username "$POSTGRES_USER"
        --dbname "$POSTGRES_DB"
        --file -
        < seeds/dev.sql
