// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/audworth/comments-system/internal/application/post (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=post . Repository
//

// Package post is a generated GoMock package.
package post

import (
	context "context"
	reflect "reflect"

	domain "github.com/audworth/comments-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ListPosts mocks base method.
func (m *MockRepository) ListPosts(ctx context.Context, params *ListParams) (*Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx, params)
	ret0, _ := ret[0].(*Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockRepositoryMockRecorder) ListPosts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockRepository)(nil).ListPosts), ctx, params)
}

// NewPost mocks base method.
func (m *MockRepository) NewPost(ctx context.Context, post *domain.Post) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPost", ctx, post)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPost indicates an expected call of NewPost.
func (mr *MockRepositoryMockRecorder) NewPost(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPost", reflect.TypeOf((*MockRepository)(nil).NewPost), ctx, post)
}

// PostByID mocks base method.
func (m *MockRepository) PostByID(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostByID", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostByID indicates an expected call of PostByID.
func (mr *MockRepositoryMockRecorder) PostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostByID", reflect.TypeOf((*MockRepository)(nil).PostByID), ctx, id)
}

// SetCommentsEnabled mocks base method.
func (m *MockRepository) SetCommentsEnabled(ctx context.Context, postID, author uuid.UUID, enabled bool) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommentsEnabled", ctx, postID, author, enabled)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCommentsEnabled indicates an expected call of SetCommentsEnabled.
func (mr *MockRepositoryMockRecorder) SetCommentsEnabled(ctx, postID, author, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommentsEnabled", reflect.TypeOf((*MockRepository)(nil).SetCommentsEnabled), ctx, postID, author, enabled)
}
