// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/audworth/comments-system/internal/application/comment (interfaces: Repository,Notifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=comment . Repository,Notifier
//

// Package comment is a generated GoMock package.
package comment

import (
	context "context"
	reflect "reflect"

	domain "github.com/audworth/comments-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CommentByID mocks base method.
func (m *MockRepository) CommentByID(ctx context.Context, id uuid.UUID) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentByID indicates an expected call of CommentByID.
func (mr *MockRepositoryMockRecorder) CommentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentByID", reflect.TypeOf((*MockRepository)(nil).CommentByID), ctx, id)
}

// ListChildren mocks base method.
func (m *MockRepository) ListChildren(ctx context.Context, params *ListParams) (*Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildren", ctx, params)
	ret0, _ := ret[0].(*Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildren indicates an expected call of ListChildren.
func (mr *MockRepositoryMockRecorder) ListChildren(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildren", reflect.TypeOf((*MockRepository)(nil).ListChildren), ctx, params)
}

// NewComment mocks base method.
func (m *MockRepository) NewComment(ctx context.Context, comment *domain.Comment) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewComment", ctx, comment)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewComment indicates an expected call of NewComment.
func (mr *MockRepositoryMockRecorder) NewComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewComment", reflect.TypeOf((*MockRepository)(nil).NewComment), ctx, comment)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyCreated mocks base method.
func (m *MockNotifier) NotifyCreated(ctx context.Context, comment *domain.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyCreated", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyCreated indicates an expected call of NotifyCreated.
func (mr *MockNotifierMockRecorder) NotifyCreated(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCreated", reflect.TypeOf((*MockNotifier)(nil).NotifyCreated), ctx, comment)
}
